conformance_automated = "Fail"
errors_diff = """
Line 51: Expected 1 errors
Line 52: Expected 1 errors
Line 55: Expected 1 errors
Line 58: Expected 1 errors
Line 82: Expected 1 errors
Line 85: Expected 1 errors
Line 86: Expected 1 errors
Line 116: Expected 1 errors
Line 119: Expected 1 errors
Line 120: Expected 1 errors
Line 122: Expected 1 errors
Line 124: Expected 1 errors
Line 125: Expected 1 errors
Line 126: Expected 1 errors
Line 151: Expected 1 errors
Line 154: Expected 1 errors
Line 155: Expected 1 errors
Line 187: Expected 1 errors
Line 190: Expected 1 errors
Line 191: Expected 1 errors
Line 193: Expected 1 errors
Line 195: Expected 1 errors
Line 196: Expected 1 errors
Line 197: Expected 1 errors
Line 236: Expected 1 errors
Line 237: Expected 1 errors
Line 240: Expected 1 errors
Line 243: Expected 1 errors
Line 273: Expected 1 errors
Line 297: Expected 1 errors
"""
output = """
callables_subtyping.py:26:5: error[invalid-assignment] Object of type `(int, /) -> int` is not assignable to `(int | float, /) -> int | float`
callables_subtyping.py:29:5: error[invalid-assignment] Object of type `(int | float, /) -> int | float` is not assignable to `(int, /) -> int`
"""
