conformance_automated = "Fail"
errors_diff = """
Line 51: Expected 1 errors
Line 54: Expected 1 errors
Line 57: Expected 1 errors
Line 66: Expected 1 errors
Line 75: Expected 1 errors
Line 118: Expected 1 errors
Line 119: Expected 1 errors
Line 135: Expected 1 errors
Line 193: Unexpected errors ['annotations_generators.py:193:1: error[type-assertion-failure] Argument does not have asserted type `() -> AsyncIterator[int]`']
"""
output = """
annotations_generators.py:86:21: error[invalid-return-type] Return type does not match returned value: expected `int`, found `types.GeneratorType`
annotations_generators.py:91:27: error[invalid-return-type] Return type does not match returned value: expected `int`, found `types.AsyncGeneratorType`
annotations_generators.py:193:1: error[type-assertion-failure] Argument does not have asserted type `() -> AsyncIterator[int]`
"""
