conformance_automated = "Fail"
errors_diff = """
Line 50: Unexpected errors ['exceptions_context_managers.py:50:5: error[type-assertion-failure] Argument does not have asserted type `int | str`']
Line 57: Unexpected errors ['exceptions_context_managers.py:57:5: error[type-assertion-failure] Argument does not have asserted type `int | str`']
"""
output = """
exceptions_context_managers.py:50:5: error[type-assertion-failure] Argument does not have asserted type `int | str`
exceptions_context_managers.py:57:5: error[type-assertion-failure] Argument does not have asserted type `int | str`
"""
