conformance_automated = "Fail"
errors_diff = """
Line 30: Expected 1 errors
Line 67: Expected 1 errors
Line 117: Expected 1 errors
Line 157: Expected 1 errors
Line 158: Expected 1 errors
Line 218: Expected 1 errors
Line 285: Expected 1 errors
Line 286: Expected 1 errors
Line 287: Expected 1 errors
Line 288: Expected 1 errors
Line 289: Expected 1 errors
Line 339: Expected 1 errors
Line 340: Expected 1 errors
Line 341: Expected 1 errors
"""
output = """
protocols_definition.py:114:1: error[invalid-assignment] Object of type `Concrete2_Bad1` is not assignable to `Template2`
protocols_definition.py:115:1: error[invalid-assignment] Object of type `Concrete2_Bad2` is not assignable to `Template2`
protocols_definition.py:116:1: error[invalid-assignment] Object of type `Concrete2_Bad3` is not assignable to `Template2`
protocols_definition.py:156:1: error[invalid-assignment] Object of type `Concrete3_Bad1` is not assignable to `Template3`
protocols_definition.py:159:1: error[invalid-assignment] Object of type `Concrete3_Bad4` is not assignable to `Template3`
protocols_definition.py:160:1: error[invalid-assignment] Object of type `Concrete3_Bad5` is not assignable to `Template3`
protocols_definition.py:219:1: error[invalid-assignment] Object of type `Concrete4_Bad2` is not assignable to `Template4`
"""
